CORE-1016 Hostagent Python Error: "AttributeError: 'str' object has no attribute 'decode'"
Removed double decode call which was causing AttributeError:'str' object has no attribute 'decode' exception.
Put decode in try except block to handle AttributeError: 'NoneType' object has no attribute 'decode' exception.