Upgrade setuptools and pip in all pf9-du builds
All pf9-du repo builds are failing due to old setuptools, pip being used on
builders. The venvs we created reuse the modules from the system pip, setuptools
and this causes the venv to fail installing certain pip packages. Errors like
below are seen
```
CertificateError: hostname 'files.pythonhosted.org' doesn't match either of
'r.ssl.fastly.net', '*.catchpoint.com', '*.cnn.io', '*.dollarshaveclub.com',
'*.eater.com', '*.fastly.picmonkey.com', '*.files.saymedia-content.com',
'*.ft.com', '*.meetupstatic.com', '*.nfl.com', '*.pagar.me', '*.picmonkey.com',
'*.realself.com', '*.sbnation.com', '*.shakr.com', '*.streamable.com',
'*.surfly.com', '*.theverge.com', '*.thrillist.com', '*.vox-cdn.com',
'*.vox.com', '*.voxmedia.com', 'eater.com', 'ft.com', 'i.gse.io',
'picmonkey.com', 'realself.com', 'static.wixstatic.com', 'streamable.com',
'surfly.com', 'theverge.com', 'vox-cdn.com', 'vox.com', 'www.joyent.com'
```

There was also an `scm_version` error during installs which is also addressed by
this.

Testing:
http://teamcity.platform9.horse/buildConfiguration/Pf9project_Pf9deploymentUnit/1479809